#!/usr/bin/env node
// Sync the lookup module's static assets from the data-pipeline output
// to the PWA's `public/data/` directory. Run after `data-pipeline all`
// (or the relevant individual subcommands) to refresh what the frontend
// ships.
//
// Usage:
//   node app/lib/lookup/scripts/sync-assets.mjs
//   npm run sync:lookup-assets
//
// The SQLite blob is copied under a **fingerprinted** filename
// `dictionary.<version>.sqlite` so its URL changes whenever the data
// pipeline produces a new build. That's how cache-busting works: the
// long-immutable HTTP cache an old visitor holds for the previous
// fingerprinted URL becomes irrelevant — the JS bundle requests a
// different URL the next time around. The new URL is recorded in
// `app/lib/lookup/dataAssets.generated.ts`, which is the only piece of
// shipped source code that "knows" the current data generation.
//
// The bktree JSONs are short-cached at the CDN edge (see scripts/
// deploy.sh) so they don't need fingerprinting — a deploy's CloudFront
// invalidation plus the 60-second revalidate window propagates them
// within a minute.

import {
  copyFile,
  mkdir,
  readFile,
  readdir,
  stat,
  unlink,
  writeFile,
} from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { existsSync } from "node:fs";

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(HERE, "..", "..", "..", "..");
const BUILD_DIR = resolve(REPO_ROOT, "tools/data-pipeline/build");
const PUBLIC_DATA_DIR = resolve(REPO_ROOT, "public/data");
const GENERATED_TS = resolve(
  REPO_ROOT,
  "app/lib/lookup/dataAssets.generated.ts",
);

const PLAIN_COPY_ASSETS = ["bktree-en.json", "bktree-my.json"];

await mkdir(PUBLIC_DATA_DIR, { recursive: true });

const versionPath = resolve(BUILD_DIR, "version.json");
if (!existsSync(versionPath)) {
  console.error(
    `Missing pipeline output: ${versionPath}\n` +
      "Run `data-pipeline all` (or `data-pipeline version`) first — " +
      "see tools/data-pipeline/README.md.",
  );
  process.exit(1);
}
const versionPayload = JSON.parse(await readFile(versionPath, "utf8"));
const version = versionPayload.version;
if (typeof version !== "string" || version.length === 0) {
  console.error(`version.json has no usable \`version\` field: ${versionPath}`);
  process.exit(1);
}

const sqliteSource = resolve(BUILD_DIR, "dictionary.sqlite");
if (!existsSync(sqliteSource)) {
  console.error(
    `Missing pipeline output: ${sqliteSource}\n` +
      "Run `data-pipeline all` (or `data-pipeline build-db`) first — " +
      "see tools/data-pipeline/README.md.",
  );
  process.exit(1);
}

const fingerprintedSqliteName = `dictionary.${version}.sqlite`;
const fingerprintedSqliteUrl = `/data/${fingerprintedSqliteName}`;
const sqliteTarget = resolve(PUBLIC_DATA_DIR, fingerprintedSqliteName);

// Drop any previous-generation SQLite blobs so `public/data/` stays
// minimal and the next `aws s3 sync --delete` purges them from S3.
for (const entry of await readdir(PUBLIC_DATA_DIR)) {
  const isOldFingerprint =
    entry.startsWith("dictionary.") &&
    entry.endsWith(".sqlite") &&
    entry !== fingerprintedSqliteName;
  const isLegacyPlain = entry === "dictionary.sqlite";
  if (isOldFingerprint || isLegacyPlain) {
    await unlink(resolve(PUBLIC_DATA_DIR, entry));
    console.log(`removed stale ${entry}`);
  }
}

await copyFile(sqliteSource, sqliteTarget);
const { size: sqliteSize } = await stat(sqliteTarget);
console.log(
  `copied dictionary.sqlite (${sqliteSize.toLocaleString()} bytes) -> ${sqliteTarget}`,
);

let missing = 0;
for (const name of PLAIN_COPY_ASSETS) {
  const source = resolve(BUILD_DIR, name);
  const target = resolve(PUBLIC_DATA_DIR, name);
  if (!existsSync(source)) {
    console.error(
      `Missing pipeline output: ${source}\n` +
        "Run `data-pipeline all` (or the relevant subcommand) first — " +
        "see tools/data-pipeline/README.md.",
    );
    missing += 1;
    continue;
  }
  await copyFile(source, target);
  const { size } = await stat(target);
  console.log(`copied ${name} (${size.toLocaleString()} bytes) -> ${target}`);
}

const generatedContents =
  `// @generated — do not edit by hand.\n` +
  `// Regenerated by app/lib/lookup/scripts/sync-assets.mjs whenever the\n` +
  `// data pipeline is re-synced into public/data/. The fingerprinted URL\n` +
  `// is what makes cache-busting work end-to-end: when the dictionary\n` +
  `// changes, the version stamp moves, the URL moves with it, and every\n` +
  `// browser fetches the new blob regardless of what it had cached for\n` +
  `// the previous generation.\n` +
  `\n` +
  `export const DATA_VERSION = ${JSON.stringify(version)};\n` +
  `export const DICTIONARY_SQLITE_URL = ${JSON.stringify(fingerprintedSqliteUrl)};\n`;
await writeFile(GENERATED_TS, generatedContents);
console.log(`wrote ${GENERATED_TS}`);

if (missing > 0) process.exit(1);
