// @generated — do not edit by hand.
// Regenerated by app/lib/lookup/scripts/sync-assets.mjs whenever the
// data pipeline is re-synced into public/data/. The fingerprinted URL
// is what makes cache-busting work end-to-end: when the dictionary
// changes, the version stamp moves, the URL moves with it, and every
// browser fetches the new blob regardless of what it had cached for
// the previous generation.

export const DATA_VERSION = "1778946792";
export const DICTIONARY_SQLITE_URL = "/data/dictionary.1778946792.sqlite";
